### ISSUE TITLE
Methods to convert a graph to tensor/matrix do not work for multigraphs

### ISSUE THREAD

**Issue by RazinShaikh** [zxcalc/pyzx#245]

**Comment by jvdwetering** [comment]
We could look at how dizx does this, as I've already solved this problem before :)

**Comment by RazinShaikh** [comment]
Nice, can you link to where it is in the code?

**Comment by jvdwetering** [comment]
Huh, I really thought I had implemented this, but there seems to be no mention of tensors anywhere in dizx. @boldar99 Do you remember whether we had support for calculating tensors in dizx?

**Comment by boldar99** [comment]
I don't recall any support for tensor contraction in dizx

**Comment by jvdwetering** [comment]
Okay, then I misremembered. Then this is not a solved problem :)

**Comment by RazinShaikh** [comment]
Closed by #258
