### ISSUE TITLE
Make ZX diagram editor compatible with newer version of ipywidgets

### ISSUE THREAD

**Issue by rafaelha** [zxcalc/pyzx#268]
The ZX diagram editor only works with older version of jupyter notebook and ipywidgets. From the docs:

```
The newer JupyterLab as opposed to the older Jupyter Notebook uses a different framework for widgets which is
currently not compatible with the widgets used in PyZX. For the editor to work you therefore must use the classic
notebook interface. If you are using JupyterLab you can find this interface by going to 
‘Help -> Launch Classic Notebook’. 
In addition, versions ipywidgets>=8 and notebook>=6.5 break the editor widget. 
The latest versions known to work is ipywidgets==7.7.1 and notebook==6.4.12.
```

Can newer version be supported? What is required to get the editor to work?

**Comment by jvdwetering** [comment]
Jupyterlab uses a completely different widget system, where you have to make a separate package of that widget and install it. I didn't look into the details, but it looked really complicated and would possibly require a lot of rewriting.
Seeing as the current version already required a lot of hacking to get the python backend and the javascript front-end to talk to each, I have no plans to do so, also considering that a much better editor now exists in the form of ZXLive, which can also be run from a Jupyter notebook and interfaces with PyZX.

**Comment by rafaelha** [comment]
One thought though: Would it be possible to relax the version requirement `ipywidgets>=7.5,<8` or turn this into an optional dependency? We're getting version solving conflicts because of this in our project.

Or would it make sense to remove the editor widget altogether, since ZXLive is the better alternative?

If any of these options looks good to you I can make a PR.

**Comment by jvdwetering** [comment]
That is definitely a thought. There is still some annoying stuff that has to be fixed in ZXLive, which I think will happen quite soon. After that I think it is a strict superset of the editor in pyzx and that can be deprecated.
